# Generated by Django 5.0.2 on 2024-02-15 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0019_complaints_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicleexit',
            name='farem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleexit',
            name='outtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
